# Generated by Django 4.1.5 on 2023-01-31 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='socialcard',
            name='back_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialcard',
            name='back_message',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='socialcard',
            name='border_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socialcard',
            name='font',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socialcard',
            name='front_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialcard',
            name='front_message',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='socialcard',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='SocialCards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='socialcard',
            name='text_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='socialcard',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
