# Generated by Django 4.1.6 on 2023-02-02 15:10

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('social_cards', '0002_follower_socialcard_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcard',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
