# Generated by Django 4.1.6 on 2023-02-06 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_cards', '0007_socialcard_border_style_socialcard_text_align'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialcard',
            name='back_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='socialcard',
            name='front_image',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
