# Generated by Django 4.1.6 on 2023-02-07 01:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_cards', '0008_alter_socialcard_back_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialcard',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='card_likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
